/**
 * Python-semantics compatibility helpers for the TS backtest engine.
 *
 * The engine in ./backtestEngine.ts is a port of `python/cli/backtest.py` and is
 * verified against `__fixtures__/*.json` (generated by
 * `python/tests/gen_backtest_fixtures.py`). Two Python behaviours have no JS
 * equivalent and are reproduced here:
 *
 * 1. `round()` — CPython rounds the *exact binary value* of the double with
 *    ties-to-even. `round(0.5) === 0`, `round(1.5) === 2`, `round(2.675, 2) === 2.67`.
 *    `Math.round` (half-up) and `toFixed` (implementation-defined on ties, and it
 *    rounds the decimal *string approximation*) are both wrong. `pyRound` rebuilds
 *    the exact decimal expansion from the IEEE-754 bits via BigInt, rounds
 *    half-to-even, and parses the resulting decimal string back to a double — the
 *    same two steps CPython performs.
 *
 * 2. Weekly bucketing — the port used to mirror `(dt.year, dt.isocalendar()[1])`, i.e.
 *    the *calendar* year combined with the *ISO* week number. That was a bug: in the
 *    week spanning New Year the key changed when the calendar year rolled over, so the
 *    week was bucketed twice and bought twice. Both implementations now use the proper
 *    ISO year-week (`dt.isocalendar()[:2]` / `isoWeekKey`), so such a week buys once.
 *    Fixture `weekly_cross_year` pins the corrected behaviour.
 */

const DAY_MS = 86_400_000;

const pow5Cache = new Map<number, bigint>();

function pow5(k: number): bigint {
  const cached = pow5Cache.get(k);
  if (cached !== undefined) return cached;
  const v = 5n ** BigInt(k);
  pow5Cache.set(k, v);
  return v;
}

/**
 * Exact decimal expansion of |x|: value === sign * digits * 10 ** exp.
 * A double is mantissa * 2 ** e, so for e < 0 it is exactly
 * (mantissa * 5 ** -e) * 10 ** e — no rounding involved.
 */
function exactDecimalParts(abs: number): { digits: bigint; exp: number } {
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, abs);
  const hi = view.getUint32(0);
  const lo = view.getUint32(4);
  const rawExp = (hi >>> 20) & 0x7ff;
  let mantissa = (BigInt(hi & 0xfffff) << 32n) | BigInt(lo);
  let exp: number;
  if (rawExp === 0) {
    exp = -1074; // subnormal: mantissa * 2 ** -1074 (no implicit bit)
  } else {
    mantissa |= 1n << 52n;
    exp = rawExp - 1075;
  }
  if (exp >= 0) return { digits: mantissa << BigInt(exp), exp: 0 };
  return { digits: mantissa * pow5(-exp), exp };
}

/** Divide `digits * 10 ** shift` to an integer, ties-to-even (in magnitude). */
function roundHalfEven(digits: bigint, shift: number): bigint {
  if (shift >= 0) return digits * 10n ** BigInt(shift);
  const divisor = 10n ** BigInt(-shift);
  const quotient = digits / divisor;
  const remainder = digits % divisor;
  const twice = remainder * 2n;
  if (twice > divisor) return quotient + 1n;
  if (twice < divisor) return quotient;
  return quotient % 2n === 0n ? quotient : quotient + 1n;
}

/**
 * CPython `round(value, digits)` for a finite double.
 * Returns a float — like CPython, the rounded decimal is parsed back to the
 * nearest double (`Number('2.67') === 2.67`).
 */
export function pyRound(value: number, digits = 0): number {
  if (!Number.isFinite(value)) return value;
  if (value === 0) return value; // preserves -0
  if (!Number.isInteger(digits)) throw new RangeError('pyRound: digits must be an integer');

  const negative = value < 0;
  const { digits: absDigits, exp } = exactDecimalParts(Math.abs(value));
  const rounded = roundHalfEven(absDigits, exp + digits);

  let text = rounded.toString();
  if (digits > 0) {
    text = text.padStart(digits + 1, '0');
    const cut = text.length - digits;
    text = `${text.slice(0, cut)}.${text.slice(cut)}`;
  }
  // Always prefix the sign: CPython returns -0.0 for e.g. round(-0.4).
  return Number(`${negative ? '-' : ''}${text}`);
}

/** ISO-8601 week-based year: the calendar year of the Thursday of `date`'s week. */
export function isoWeekYear(year: number, month: number, day: number): number {
  const date = Date.UTC(year, month - 1, day);
  const dow = (new Date(date).getUTCDay() + 6) % 7; // Mon = 0 … Sun = 6
  return new Date(date + (3 - dow) * DAY_MS).getUTCFullYear();
}

/** ISO-8601 week number (Mon-first, week of the first Thursday), for a UTC calendar date. */
export function isoWeekNumber(year: number, month: number, day: number): number {
  const date = Date.UTC(year, month - 1, day);
  const dow = (new Date(date).getUTCDay() + 6) % 7; // Mon = 0 … Sun = 6
  const thursday = date + (3 - dow) * DAY_MS;
  const isoYear = new Date(thursday).getUTCFullYear();
  const jan4 = Date.UTC(isoYear, 0, 4);
  const jan4Dow = (new Date(jan4).getUTCDay() + 6) % 7;
  const week1Monday = jan4 - jan4Dow * DAY_MS;
  return Math.round((thursday - week1Monday) / (7 * DAY_MS)) + 1;
}

/**
 * Weekly bucket key: the ISO year-week, matching `dt.isocalendar()[:2]`.
 * The week spanning New Year keeps a single key (see the header note).
 */
export function isoWeekKey(dateStr: string): string {
  const [y, m, d] = dateStr.split('-').map(Number);
  return `${isoWeekYear(y, m, d)}-W${isoWeekNumber(y, m, d)}`;
}

/** Monthly bucket key, matching `(dt.year, dt.month)` from backtest.py. */
export function monthKey(dateStr: string): string {
  const [y, m] = dateStr.split('-').map(Number);
  return `${y}-${String(m).padStart(2, '0')}`;
}

/** Day-of-year index used to compare dates without allocating Date objects. */
export function dayStamp(dateStr: string): number {
  const [y, m, d] = dateStr.split('-').map(Number);
  return Date.UTC(y, m - 1, d);
}

/** Monday-based weekday index (Mon = 0 … Sun = 6). */
export function weekdayIndex(dateStr: string): number {
  const [y, m, d] = dateStr.split('-').map(Number);
  return (new Date(Date.UTC(y, m - 1, d)).getUTCDay() + 6) % 7;
}

/** Day of month, 1–31. */
export function dayOfMonth(dateStr: string): number {
  return Number(dateStr.slice(8, 10));
}
